### ISSUE TITLE
Transaction functions should throw an error in case of failure

### ISSUE THREAD

**Issue by krlmlr** [rstats-db/DBI#112]
Current specification: Return a logical that indicates success.

**Comment by krlmlr** [comment]
The return value of `dbBegin()` should be an object that can be passed to `dbCommit()` and `dbRollback()`. Then, the connection pool can implement `dbBegin()` which calls `$fetch()` but not `$release()`, and also `dbCommit()` and `dbRollback()`.

CC @bborgesr.

**Comment by bborgesr** [comment]
I think the original idea is that the connection pool won't implement the transaction methods at all (or rather, it will always throw an error for these methods), with the exception of `dbWithTransaction` once this is on CRAN. 
We could revisit that, but I think it makes sense for these things to be strictly `DBIConnection` methods and not `Pool` methods. To clarify, you can still use these in the context of the pool, but you'll have to first actually fetch a connection yourself using `conn <- pool$fetch()` (aside: this will soon be changed to a normal-looking function, rather than an R6 method: `conn <- poolCheckout(pool)`). And then you can use the transaction methods as usual (ex: `dbBegin(conn)`).

cc @hadley, @jcheng5

**Comment by krlmlr** [comment]
If the connection pool doesn't implement dbBegin() et al., it's not DBI-compliant, strictly speaking ;-)

This issue is about making dbBegin() work even for the connection pool.

**Comment by jcheng5** [comment]
@krlmlr Just so we're clear, `dbBegin` today just operates on a connection and has the side-effect of starting a transaction; you're proposing a change that `dbBegin` return some kind of transaction handle, so that this would make it possible for the connection pool to fully implement `dbBegin`. This wouldn't actually work unless the object returned from `dbBegin` is passed not only to `dbCommit` and `dbRollback`, but also every `dbExecQuery`, `dbGetQuery`, etc. I think it's just a bad fit for the pool.

Also, to return connections to the pool, the pool needs to be able to rollback any outstanding transaction on the connection, and changing the `dbBegin` semantics the way you're proposing will make that harder.

I think it's OK for the pool not to be strictly DBI-compliant; it acts as both a driver-like and connection-like object, which is weird enough already. The semantics are going to be fundamentally different than a true connection, I think we're already lucky enough that so many of the DBI connection methods work as well with it as they do. The transaction-oriented ones are just a really bad fit though.

**Comment by krlmlr** [comment]
Clearly, I haven't thought beyond dbCommit() here ;-)

A question: Under what circumstances is there more than one *active* connection in a connection pool? I thought that a Shiny app can make do with at most one active connection per R session at any time, but I might be missing a point.

**Comment by bborgesr** [comment]
So, the idea is that there would be a connection pool per R process, not per Shiny app (@jcheng5 correct me if I'm wrong). This would allow, for example, several users to connect to the same app (therefore opening several instances of the same app) and share the same connection pool. Another possibility is that even within the same app, you might need more than one connection at a time because you might be doing some complicated transaction some place and some regular fetching some other place, at the same time. But all that said, yes, I feel that the most common use case will still be just one active connection at a time, at least in the beginning. Still, all the benefits of connection management and performance apply :)

**Comment by krlmlr** [comment]
I'm sure you have considered an alternative design, where the DBIConnection object supplied by the connection pool is just a very thin wrapper that releases the connection to the pool when dbDisconnect() is called. This does require an explicit dbConnect() and dbDisconnect() for each operation, but the behavior of the connection pool seems to be more predictable and easier to understand/implement.

```R
con <- dbConnect(pool)
on.exit(dbDisconnect(con))
...
```

This could be wrapped, too:

```R
withConnection(pool, {
...
})
```

**Comment by hadley** [comment]
@krlmlr yeah, we definitely considered that, but people can already write code pretty similar to that. The goal of this interface is to provide a safe way of accessing databases that is very easy to use.

**Comment by jcheng5** [comment]
@krlmlr The pool package supports that usage style, too (right, @bborgesr?), though we don't have the `withConnection` wrapper at the moment. FWIW, this was how I always pictured people using the connection pool, until talking to Hadley about it a few weeks ago--the mental model is definitely simple to understand and simple to implement. But Hadley's right that having the pool stand-in directly for a connection is suitable for the vast majority of common use cases in R, and is almost impossible for users to screw up (i.e. forgetting to dbDisconnect).

**Comment by bborgesr** [comment]
Yes, @jcheng5 is right on all counts. You can totally use that pattern, and use the pool really just as a driver. But, like Joe mentioned, most people probably don't need that level of control and this makes connection management a no brainer. Given that you can always use the pool as a stand-in for a connection (with the very rare exception of complicated/interactive transactions), I don't think a `withConnection` is warranted (and it would do nothing still for the case of complicated/interactive transactions).

**Comment by krlmlr** [comment]
Keeping the interface "as is", closing in favor of https://github.com/rstats-db/DBItest/issues/104.
