### ISSUE TITLE
allow additional unused params for dbBind

### ISSUE THREAD

**Issue by metanoid** [rstats-db/DBI#159]
I was previously using `RSQLite::dbSendPreparedQuery`- but I see that it is deprecated in favour of `DBI::dbSendStatement` + `DBI::dbBind`

My previous usage was to pass a data.frame as the `bind.data` argument, as well as a SQL statement with named placeholders (in the style of `:column_name` ).

With `dbSendPreparedQuery` - if I had additional columns in the data.frame (which I often do) - then this was not an issue.  However, dbBind throws an error along the lines of 
```
Warning: Error in rsqlite_bind_rows: Query requires 6 params; 10 supplied.
```

Is it possible to check whether all placeholders are named, and, if so, using just those columns in the query?  This would save the user from having to type out which subset of columns they want used every time.

**Comment by krlmlr** [comment]
Thanks. I'd rather not change this behavior, because it offers an additional free consistency check. Even if it may be a little more work to write, it will help detect errors if you change your code later and forget to update the data, or vice versa.

Currently, there's no API to retrieve the names of the arguments in a query. We could consider adding a `dbGetParams(DBIResult, ...)` generic that returns the variable names used in a query, so that you could do the filtering yourself.

I'm curious, is this for a package or for user code?

**Comment by metanoid** [comment]
As with many of my projects in R, this started out as a short one-off script, and the longer the project goes on, the more I wish I had structured it as a package to begin with :-)
But it's for user code - I have a large shiny dashboard to allow users to upload their files.  I tease apart the various data elements of the uploaded files, and store them in a sqlite database.
You're right that it does create a consistency check, and that is useful.
I've changed over all my code to `dplyr::select` only the columns that are needed, just before the `dbBind` call, and that works well, even if it was a bit tedious to implement.

Closing.
