### ISSUE TITLE
Add dbSendUpdate or equivalent to DBI

### ISSUE THREAD

**Issue by macqdh** [rstats-db/DBI#20]
Please add a function like RJDBC::dbSendUpdate to DBI so that it will be available for other db access packages such as ROracle. See the R-sig-DB thread starting with https://stat.ethz.ch/pipermail/r-sig-db/2014q3/001443.html for more information and discussion, including alternate name and some implementation details.

**Comment by krlmlr** [comment]
The number of affected rows might be interesting here as well.

**Comment by hadley** [comment]
Might be better to return `dbGetRowsAffected()`.

**Comment by imanuelcostigan** [comment]
More general question: what do you define as a "query"? Here's the [SQL wikipedia entry for query](https://en.wikipedia.org/wiki/SQL#Queries):

> The most common operation in SQL, the query, makes use of the declarative SELECT statement.

If this is correct, then using `dbSendQuery` to denote sending any command to the DB is probably misleading. Something like `dbExecute` or `dbSendUpdate` might better distinguish the two.

@hadley that implementation will be tricky for JDBC based backends. [RJDBC's `dbSendQuery` method](https://github.com/s-u/RJDBC/blob/1b7ccd4677ea49a93d909d476acf34330275b9ad/R/class.R#L78) wraps the `executeQuery` method and expects a `ResultSet` return value. `CREATE` or `UPDATE` commands do not return such a result and therefore must be executed using [`dbSendUpdate`](https://github.com/s-u/RJDBC/blob/1b7ccd4677ea49a93d909d476acf34330275b9ad/R/class.R#L108) which **does not** return a `ResultSet`. It is possible to avoid this approach by overriding RJDBC's `dbSendQuery` method so that it wraps [JDBC's `execute`](http://docs.oracle.com/javase/7/docs/api/java/sql/Statement.html#execute(java.lang.String)) rather than `executeQuery` method, but I'm sure @s-u has a good reason for not doing so.

@krlmlr note also that `DBItest` assumes you can create, update tables using `dbSendQuery` in the `command_query` subtest of the `test_result` function

**Comment by hadley** [comment]
If it wasn't clear, I meant the code sample to be a default method that could be overridden by specific back ends that need to do something differently.

**Comment by krlmlr** [comment]
Makes sense to me:

- Define a generic dbExecute() (or dbSendUpdate(), or ...)
- Default implementation in DBI forwards to dbSendQuery()
- Backends are free to override the DBI implementation (seems helpful at least for JDBC)
- Need to use the new function in DBItest, too

Still unclear:

- Asynchronous execution (#69)?
- Return value?

**Comment by hadley** [comment]
I think it should block for now, and then when we figure out a good approach for async get/send we can implement it for execute too.

I think that since `dbExecute()` is called primarily for its side effect, it should return `invisible(con)`

**Comment by krlmlr** [comment]
We still need a dbSendUpdate() which is called by dbExecute().

**Comment by hadley** [comment]
@krlmlr why?

**Comment by krlmlr** [comment]
- Prepared statements like `INSERT INTO t VALUES (?, ?)` needs an object against which dbBind() can be called
- dbExecute() contains boilerplate which I'd rather not see duplicated in backends
- There's a nice symmetry with dbSendQuery/dbGetQuery and dbSendUpdate/dbExecute

I'd even like to define a new class DBIStatus, objects of this class would be returned by dbSendUpdate[Async](), to make DBIResult a bit lighter weight.

**Comment by woblak** [comment]
is the issue solved? What is the function to run non-queries in DBI called? I am asking becuz I still must run `RJDBC::dbSendUpdate(conn, "insert into mytable (mycolumn) values ('aaa')")` instead of `DBI::???`

**Comment by krlmlr** [comment]
@woblak: Can you please take this to the maintainer of _RJDBC_?
