### ISSUE TITLE
Implicit dbDisconnect()

### ISSUE THREAD

**Issue by krlmlr** [rstats-db/DBI#89]
...could be achieved via `reg.finalizer()`. Need to find a way to test it.

We still want to allow an explicit disconnect (e.g., https://github.com/rstats-db/DBI/issues/87#issuecomment-193825248).

**Comment by hadley** [comment]
I think best practice is to close on `gc()` with a warning, if not already explicitly closed. We want to encourage people to close explicitly (since that might be much earlier than a GC), but not penalise them if they forget.

Rather than using `reg.finalizer()` it should be done at the driver level with a finaliser on the external pointer.

**Comment by krlmlr** [comment]
Will be tested by DBItest.
